[build]
    publish = "dist"
    command = "npm run build"

[[redirects]]
    from = "/*"
    to = "/404.html"
    status = 404

[[redirects]]
  from = "https://bazar.conedevelopment.com/*"
  to = "https://root.conedevelopment.com/docs/extensions/bazar/"
  status = 301
  force = true
